### ISSUE TITLE
Sup

### ISSUE THREAD

**Issue by kotovdv** [yuraguz/UnityTopView2DGame#1]
Got tired of enterprise java shit as well? :)

**Comment by yuraguz** [comment]
Exactly :) Otherwise you can die of boredom...

**Comment by kotovdv** [comment]
I feel you, bruh.

**Comment by yuraguz** [comment]
I also played with [Phaser](https://phaser.io/) and made prototype of game in genre "Idle Clicker" but now interested in how to make it in Unity because in Phaser I had to write a lot of things that Unity provides out of the box
